---
### 🏆 جوائز GitHub
<p align="center">
  <img src="https://github-profile-trophy.vercel.app/?username=clawvision&theme=tokyonight&no-frame=true&row=1&column=6"/>
</p>

---
### 🐍 رسم بياني للمساهمة
<p align="center">
  <img src="https://raw.githubusercontent.com/clawvision/clawvision/output/github-contribution-grid-snake.svg" alt="snake"/>
</p>
